/**
 * Model introspection and query builders for Kibo CMS 6.x Headless CMS.
 *
 * Assumes Kibo CMS 6.x: content fields always live under `values { … }` in list
 * responses and are sent flat in create/update `$data` inputs.
 *
 * Introspection (introspectModels) is only used as a fallback when no
 * --schema-file is provided.  The preferred path is to load model definitions
 * from a Kibo CMS model export JSON (see schema.ts / loadSchemaFile).
 */

import { GraphQLClient, logger } from "@kibo-cms-clone-tool/shared";

// Fields generated by Kibo CMS that cannot be written back
export const SYSTEM_FIELDS = new Set([
  "createdOn",
  "savedOn",
  "createdBy",
  "ownedBy",
  "webinyVersion",
]);

export interface FieldDefinition {
  fieldId: string;
  type: string;
  multipleValues: boolean;
  settings?: Record<string, unknown>;
}

export interface ModelDefinition {
  modelId: string;
  name: string;
  pluralApiName: string;
  fields: FieldDefinition[];
  listOperation: string;
  createOperation: string;
  updateOperation: string;
  publishOperation: string;
  deleteOperation: string;
  whereInputType: string;
}

// ── Fallback: API-based model discovery ───────────────────────────────────────
// Used only when --schema-file is not provided.

const LIST_MODELS_QUERY = /* GraphQL */ `
  query ListContentModels {
    listContentModels {
      data {
        modelId
        name
        singularApiName
        pluralApiName
        fields { fieldId type list settings }
      }
      error { message }
    }
  }
`;

interface RawModelEntry {
  modelId: string;
  name: string;
  singularApiName?: string | null;
  pluralApiName?: string | null;
  // Kibo CMS's CmsContentModelField uses `list` (not `multipleValues`).
  fields: Array<{ fieldId: string; type: string; list?: boolean; settings?: Record<string, unknown> }>;
}

interface ListContentModelsResponse {
  listContentModels: { data: RawModelEntry[]; error: { message: string } | null };
}

function derivePluralApiName(modelId: string): string {
  if (modelId.endsWith("s") || modelId.endsWith("x") || modelId.endsWith("z")) return modelId + "es";
  if (modelId.endsWith("y") && !/[aeiou]y$/.test(modelId)) return modelId.slice(0, -1) + "ies";
  return modelId + "s";
}

function normaliseModels(raw: RawModelEntry[]): Array<{ modelId: string; name: string; singularApiName: string; pluralApiName: string; fields: FieldDefinition[] }> {
  return raw.map((m) => ({
    modelId: m.modelId,
    name: m.name,
    singularApiName: m.singularApiName || m.modelId,
    pluralApiName: m.pluralApiName || derivePluralApiName(m.modelId),
    fields: (m.fields ?? []).map((f) => ({
      fieldId: f.fieldId,
      type: f.type,
      multipleValues: f.list ?? false,
      settings: f.settings,
    })),
  }));
}

/** Capitalize first letter. */
export function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

async function fetchContentModels(
  adminClient: GraphQLClient,
  manageClient: GraphQLClient
): Promise<Array<{ modelId: string; name: string; singularApiName: string; pluralApiName: string; fields: FieldDefinition[] }>> {
  let lastErr: unknown;
  for (const client of [adminClient, manageClient]) {
    try {
      const resp = await client.request<ListContentModelsResponse>(LIST_MODELS_QUERY, undefined, { maxAttempts: 1 });
      if (resp.listContentModels?.data) {
        return normaliseModels(resp.listContentModels.data);
      }
    } catch (e) { lastErr = e; /* try next client */ }
  }

  const diagQuery = `{ __schema { queryType { fields { name } } } }`;
  logger.error("\n❌ Could not find listContentModels on any known endpoint.");
  for (const [label, client] of [["Admin", adminClient], ["Manage", manageClient]] as const) {
    try {
      const s = await client.request<{ __schema: { queryType: { fields: Array<{ name: string }> } } }>(
        diagQuery, undefined, { maxAttempts: 1 }
      );
      logger.error(`   ${label} API query fields: ${s.__schema.queryType.fields.map((f) => f.name).join(", ")}`);
    } catch {
      logger.error(`   ${label} API: schema introspection failed`);
    }
  }
  logger.error("\n   Check SOURCE_ADMIN_GQL_URL and SOURCE_MANAGE_URL in your .env");
  // Keep the underlying error (e.g. "HTTP 401") in the message so callers can
  // distinguish auth failures from a genuinely missing operation.
  const detail = lastErr instanceof Error ? lastErr.message.split("\n")[0] : String(lastErr ?? "");
  throw new Error(`listContentModels not found — see diagnostic output above${detail ? ` (last error: ${detail})` : ""}`);
}

export async function introspectModels(
  manageClient: GraphQLClient,
  requestedModels: string[],
  adminClient?: GraphQLClient
): Promise<Map<string, ModelDefinition>> {
  const effectiveAdminClient = adminClient ?? manageClient;
  const allModels = await fetchContentModels(effectiveAdminClient, manageClient);

  const all = requestedModels.length === 1 && requestedModels[0].toUpperCase() === "ALL";
  const result = new Map<string, ModelDefinition>();

  for (const model of allModels) {
    // Skip Kibo CMS/Kibo system models (webhooks, languages, tenant, background tasks).
    if (/^(wby|webhook|backgroundTask)/i.test(model.modelId)) continue;
    if (!all && !requestedModels.some((r) => r.toLowerCase() === model.name.toLowerCase())) {
      continue;
    }

    const writableFields = model.fields.filter((f: FieldDefinition) => !SYSTEM_FIELDS.has(f.fieldId));
    // Operation + input-type names are built from the API names, not the modelId.
    const capSingular = capitalize(model.singularApiName);
    const capPlural = capitalize(model.pluralApiName);

    result.set(model.name, {
      modelId: model.modelId,
      name: model.name,
      pluralApiName: model.pluralApiName,
      fields: writableFields,
      listOperation: `list${capPlural}`,
      createOperation: `create${capSingular}`,
      updateOperation: `update${capSingular}`,
      publishOperation: `publish${capSingular}`,
      deleteOperation: `delete${capSingular}`,
      whereInputType: `${capSingular}ListWhereInput`,
    });
  }

  if (!all) {
    for (const requested of requestedModels) {
      if (![...result.keys()].some((k) => k.toLowerCase() === requested.toLowerCase())) {
        logger.warn(`  ⚠  Model "${requested}" not found in source environment`);
      }
    }
  }

  return result;
}

/**
 * Extract a model field that can be dropped from the selection set and retried,
 * from a GraphQL error. Handles two cases:
 *   - corrupt stored data:  …in field "rich-text@xx" - description.   (Kibo CMS fromStorage)
 *   - selection-shape error: Cannot query field "X" … /
 *                            Field "X" must (not)? have a selection …
 * Returns the candidate fieldId, or null. The caller MUST verify the returned id
 * is an actual model field before skipping (so an operation-name error like
 * `Cannot query field "listFoos"` is not mistaken for a droppable field).
 */
export function parseSkippableField(err: unknown): string | null {
  const msg = err instanceof Error ? err.message : String(err);
  const corrupt = msg.match(/ in field "[^"]*"\s*-\s*([A-Za-z0-9_]+)\.?/);
  if (corrupt) return corrupt[1];
  const selection = msg.match(/(?:Cannot query field|Field) "([A-Za-z0-9_]+)"/);
  if (selection) return selection[1];
  return null;
}

// ── Selection-set + query builders ───────────────────────────────────────────

/**
 * Build a single field's GQL selection line.
 *
 * Kibo CMS 6.x field types:
 *   ref        → { id entryId modelId }
 *   file       → { id key name src type }
 *   object     → recursively expand sub-fields from settings.fields
 *   everything else (text, number, boolean, rich-text, …) → scalar, no selection
 */
function buildFieldLine(field: FieldDefinition, depth = 0): string {
  const pad = "  ".repeat(depth);

  if (field.type === "ref") {
    return `${field.fieldId} { id entryId modelId }`;
  }

  if (field.type === "file") {
    // Kibo CMS 6.x Manage API: file fields under values{} are scalar strings
    // (file reference ID or CDN URL) — no sub-selection.
    return field.fieldId;
  }

  if (field.type === "object") {
    type RawSubField = { fieldId: string; type: string; list?: boolean; settings?: Record<string, unknown> };
    const subFields = field.settings?.fields as RawSubField[] | undefined;
    if (subFields && subFields.length > 0) {
      const lines = subFields
        .map((sf) =>
          buildFieldLine(
            { fieldId: sf.fieldId, type: sf.type, multipleValues: sf.list ?? false, settings: sf.settings },
            depth + 1
          )
        )
        .join(`\n${pad}    `);
      return `${field.fieldId} {\n${pad}    ${lines}\n${pad}  }`;
    }
    // No sub-fields known — emit scalar-style; GQL will surface an error if wrong
    return field.fieldId;
  }

  // Scalar: text, number, boolean, rich-text, long-text, etc.
  return field.fieldId;
}

/**
 * Build the GraphQL selection set for a model's list query.
 *
 * Kibo CMS 6.x: content fields always live under `values { … }`.
 * System fields (id, entryId) are selected at the entry root.
 */
export function buildSelectionSet(
  fields: FieldDefinition[],
  skipFields?: Set<string>,
  fieldLines?: Map<string, string>,
  extraRootLines?: string[]
): string {
  // Prefer introspection-derived selection lines (precise per-field shape) when
  // provided; otherwise fall back to the heuristic per-type builder.
  const contentLines = fieldLines
    ? [...fieldLines.entries()].filter(([fid]) => !skipFields?.has(fid)).map(([, line]) => line)
    : fields
        .filter((f) => !SYSTEM_FIELDS.has(f.fieldId))
        .filter((f) => !skipFields?.has(f.fieldId))
        .map((f) => buildFieldLine(f));

  return [
    "id",
    "entryId",
    `values {\n          ${contentLines.join("\n          ")}\n        }`,
    // Root-level lines (e.g. wbyAco_location { folderId }) sit beside `values`.
    ...(extraRootLines?.filter((l) => !!l) ?? []),
  ].join("\n        ");
}

/**
 * Build the list query for a model.
 *
 * - $after is only declared when cursor is provided (avoids servers that
 *   reject a declared-but-absent nullable variable).
 * - $where is only declared when whereFilter is provided (avoids type-name
 *   mismatches when no filter is needed).
 */
export function buildListQuery(
  model: ModelDefinition,
  whereFilter?: Record<string, unknown>,
  cursor?: string | null,
  skipFields?: Set<string>,
  fieldLines?: Map<string, string>,
  extraRootLines?: string[]
): string {
  const selectionSet = buildSelectionSet(model.fields, skipFields, fieldLines, extraRootLines);

  const vars: string[] = [];
  const args: string[] = ["limit: 50"];

  if (cursor) {
    vars.push("$after: String");
    args.push("after: $after");
  }
  if (whereFilter) {
    vars.push(`$where: ${model.whereInputType}`);
    args.push("where: $where");
  }

  const varDecl = vars.length ? `(${vars.join(", ")})` : "";
  const argList = args.join(", ");

  return /* GraphQL */ `
    query List${capitalize(model.pluralApiName)}${varDecl} {
      ${model.listOperation}(${argList}) {
        data {
          ${selectionSet}
        }
        meta {
          cursor
          hasMoreItems
          totalCount
        }
        error {
          message
        }
      }
    }
  `;
}

/**
 * The capitalized singular API name, derived from the create operation
 * (`create<Cap>` → `<Cap>`). The input type is `<Cap>Input`.
 */
function opModel(model: ModelDefinition): string {
  return model.createOperation.replace(/^create/, "");
}

/** Build create mutation for a model. */
export function buildCreateMutation(model: ModelDefinition): string {
  const cap = opModel(model);
  return /* GraphQL */ `
    mutation Create${cap}($data: ${cap}Input!) {
      ${model.createOperation}(data: $data) {
        data { id entryId }
        error { message code }
      }
    }
  `;
}

/** Build update mutation for a model. */
export function buildUpdateMutation(model: ModelDefinition): string {
  const cap = opModel(model);
  return /* GraphQL */ `
    mutation Update${cap}($revision: ID!, $data: ${cap}Input!) {
      ${model.updateOperation}(revision: $revision, data: $data) {
        data { id entryId }
        error { message code }
      }
    }
  `;
}

/** Build publish mutation for a model. */
export function buildPublishMutation(model: ModelDefinition): string {
  const cap = opModel(model);
  return /* GraphQL */ `
    mutation Publish${cap}($revision: ID!) {
      ${model.publishOperation}(revision: $revision) {
        data { id entryId }
        error { message }
      }
    }
  `;
}

/** Build delete mutation for a model. Deletes the entry and all its revisions. */
/**
 * Delete an entry. `options: { permanently: false }` is REQUIRED for a soft
 * delete (entry goes to the bin / recoverable) — without it the API hard-deletes.
 * Pass permanently=true only for an unrecoverable purge.
 */
export function buildDeleteMutation(model: ModelDefinition, permanently = false): string {
  const cap = opModel(model);
  return /* GraphQL */ `
    mutation Delete${cap}($revision: ID!) {
      ${model.deleteOperation}(revision: $revision, options: { permanently: ${permanently} }) {
        data
        error { message }
      }
    }
  `;
}
