/**
 * Import step: read exported files.json from disk,
 * recreate folder structure in target,
 * register each file's metadata in target File Manager,
 * write s3-copy-manifest.txt for the binary copy.
 */

import fs from "fs";
import path from "path";
import pLimit from "p-limit";
import {
  GraphQLClient,
  logger,
  syncFolders,
  validateFolderMapping,
  formatFolderValidation,
  FolderAdapter,
  FolderSyncResult,
} from "@kibo-cms-clone-tool/shared";
import {
  getExistingFile,
  createFileInTarget,
  updateFileLocationInTarget,
  fetchAllTargetFolders,
  createFolderInTarget,
  FileRecord,
} from "./files";
import { ExportFile } from "./export";
import { ImportConfig } from "./config";

export interface ImportStats {
  total: number;
  skipped: number;
  registered: number;
  folderUpdated: number;
  errors: Array<{ key: string; id: string; error: string }>;
}

export function readExportFile(dir: string): ExportFile {
  const filePath = path.join(dir, "files.json");
  if (!fs.existsSync(filePath)) {
    throw new Error(`Export file not found: ${filePath}`);
  }
  return JSON.parse(fs.readFileSync(filePath, "utf-8")) as ExportFile;
}

/**
 * Folder adapter: bridges the shared folder engine to the File Manager / ACO
 * folder API (discovery + fall-through live in files.ts).
 */
function fileFolderAdapter(targetClient: GraphQLClient): FolderAdapter {
  return {
    listTargetFolders: () => fetchAllTargetFolders(targetClient),
    createFolder: async ({ name, slug, parentId }) => {
      const created = await createFolderInTarget(targetClient, name, slug, parentId);
      return created.id;
    },
  };
}

async function processFile(
  file: FileRecord,
  targetClient: GraphQLClient,
  config: ImportConfig,
  exportSourceCdnDomain: string,
  folderIdMap: Map<string, string>
): Promise<{ action: "skipped" | "registered" | "folderUpdated" | "error"; error?: string }> {
  if (config.dryRun) {
    return { action: "registered" }; // count as "would register"
  }

  try {
    // Resolve target folder ID from the source folder map
    const sourceFolderId = file.location?.folderId ?? null;
    const targetFolderId = sourceFolderId ? (folderIdMap.get(sourceFolderId) ?? null) : null;

    // Check whether the file already exists in the target
    const existing = await getExistingFile(targetClient, file.key);

    if (existing) {
      if (!config.skipExisting) {
        // skipExisting=false means re-register (treat as new) — fall through to create
      } else {
        // File exists — check if it needs to be moved to the correct folder
        const existingFolderId = existing.location?.folderId ?? null;
        if (targetFolderId && existingFolderId !== targetFolderId) {
          await updateFileLocationInTarget(targetClient, existing.id, targetFolderId);
          return { action: "folderUpdated" };
        }
        return { action: "skipped" };
      }
    }

    await createFileInTarget(
      targetClient,
      file,
      exportSourceCdnDomain || config.sourceCdnDomain,
      config.targetCdnDomain,
      targetFolderId ?? undefined
    );
    return { action: "registered" };
  } catch (err) {
    return {
      action: "error",
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

function writeS3Manifest(files: FileRecord[], config: ImportConfig): void {
  const manifestPath = path.resolve(process.cwd(), "s3-copy-manifest.txt");

  const lines = [
    "# S3 Copy Manifest — generated by Kibo CMS file-manager cloner",
    `# Source bucket : ${config.sourceS3Bucket}`,
    `# Target bucket : ${config.targetS3Bucket}`,
    `# Generated at  : ${new Date().toISOString()}`,
    "#",
    "# Option A — Sync entire files prefix (recommended for full cloning):",
    `#   aws s3 sync s3://${config.sourceS3Bucket}/${config.sourceS3Prefix} s3://${config.targetS3Bucket}/${config.sourceS3Prefix}`,
    "#",
    "# Option B — Copy individual files listed below:",
    ...files.map(
      (f) =>
        `aws s3 cp "s3://${config.sourceS3Bucket}/${f.key}" "s3://${config.targetS3Bucket}/${f.key}"`
    ),
  ];

  fs.writeFileSync(manifestPath, lines.join("\n"), "utf-8");
  logger.log(`\n📄 S3 copy manifest written to: ${manifestPath}`);
  logger.log(`   Share with your AWS admin to copy ${files.length} file(s).`);
}

export async function importFiles(
  targetClient: GraphQLClient,
  exportFile: ExportFile,
  config: ImportConfig
): Promise<ImportStats> {
  const { files, folders = [] } = exportFile;

  // Step 1: sync folder tree, get sourceId→targetId map.
  // Folder creation is best-effort — if the target Kibo CMS instance doesn't
  // expose a folder API at all, skip it and import all files flat (no folder).
  let folderIdMap = new Map<string, string>();
  let sync: FolderSyncResult | null = null;
  try {
    sync = await syncFolders(fileFolderAdapter(targetClient), folders, {
      dryRun: config.dryRun,
      label: "folder",
      logger,
    });
    folderIdMap = sync.idMap;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.warn(`\n  ⚠  Folder sync skipped — folder API unavailable on this target:`);
    logger.warn(`     ${msg.split("\n")[0]}`);
    logger.warn(`     Files will be imported without folder assignment.\n`);
  }

  // Step 1b: validate that every file's folder resolved before importing.
  // Blocks (unless --allow-folder-mismatch) so files don't silently land at root.
  if (sync && !config.dryRun) {
    const refs = files.map((f) => ({ itemId: f.id, folderId: f.location?.folderId ?? null }));
    const report = validateFolderMapping(refs, sync);
    if (!report.ok) {
      formatFolderValidation(report, "file").forEach((l) => logger.warn(`  ${l}`));
      if (!config.allowFolderMismatch) {
        throw new Error(
          `Folder validation failed: ${report.issues.length} file(s) reference folders ` +
            `that did not sync to the target. Pass --allow-folder-mismatch to import anyway.`
        );
      }
    }
  }

  // Step 2: register file metadata
  const stats: ImportStats = {
    total: files.length,
    skipped: 0,
    registered: 0,
    folderUpdated: 0,
    errors: [],
  };

  logger.log(`\n  Registering ${files.length} files in target...`);

  const limit = pLimit(config.concurrency);
  let processed = 0;

  const tasks = files.map((file) =>
    limit(async () => {
      const result = await processFile(
        file,
        targetClient,
        config,
        exportFile.sourceCdnDomain,
        folderIdMap
      );

      if (result.action === "skipped") stats.skipped++;
      else if (result.action === "registered") stats.registered++;
      else if (result.action === "folderUpdated") stats.folderUpdated++;
      else {
        stats.errors.push({ key: file.key, id: file.id, error: result.error ?? "unknown" });
      }

      processed++;
      if (processed % 50 === 0 || processed === files.length) {
        logger.write(`\r  Progress: ${processed}/${files.length}`);
      }
    })
  );

  await Promise.all(tasks);
  logger.write("\n");

  // Always write the S3 manifest (even in dry-run, so it can be shared)
  writeS3Manifest(files, config);

  return stats;
}
